"""Tests for F103: All PNG visualization files are real images generated by matplotlib.

This test verifies that all .png files in demo output are actual image files,
not text placeholders.
"""

import subprocess
from pathlib import Path

import pytest


class TestF103RealPNGImages:
    """Test F103: All PNG files are real images, not text files."""

    @pytest.fixture(scope="class")
    def demo_output_dir(self) -> Path:
        """Get the demo output directory path and ensure demo has run."""
        output_dir = Path("demo_output/nangate45_extreme_demo")

        # Run demo if output doesn't exist
        if not output_dir.exists() or not (output_dir / "summary.json").exists():
            result = subprocess.run(
                ["bash", "demo_nangate45_extreme.sh"],
                capture_output=True,
                timeout=1800,
            )
            if result.returncode != 0:
                pytest.fail(f"Demo failed to execute: {result.stderr}")

        return output_dir

    def test_step_1_generate_heatmap_visualizations_from_demo(
        self, demo_output_dir: Path
    ) -> None:
        """Step 1: Generate heatmap visualizations from demo."""
        # Demo should already be run by fixture
        assert demo_output_dir.exists(), "Demo output directory not found"
        assert (demo_output_dir / "summary.json").exists(), "Demo did not complete"

    def test_step_2_verify_all_png_files_have_size_greater_than_1000_bytes(
        self, demo_output_dir: Path
    ) -> None:
        """Step 2: Verify all .png files have size > 1000 bytes."""
        # Find all PNG files
        png_files = list(demo_output_dir.rglob("*.png"))
        assert len(png_files) > 0, "No PNG files found in demo output"

        # Check each PNG file size
        small_files = []
        for png_file in png_files:
            size = png_file.stat().st_size
            if size <= 1000:
                small_files.append((png_file, size))

        assert len(small_files) == 0, (
            f"Found {len(small_files)} PNG files <= 1000 bytes (likely text placeholders): "
            f"{[(str(f), s) for f, s in small_files[:5]]}"
        )

    def test_step_3_run_file_and_verify_png_file_type(
        self, demo_output_dir: Path
    ) -> None:
        """Step 3: Run file <png> and verify file type is PNG image data."""
        # Find all PNG files
        png_files = list(demo_output_dir.rglob("*.png"))
        assert len(png_files) > 0, "No PNG files found in demo output"

        # Check file type for each PNG
        non_image_files = []
        for png_file in png_files:
            result = subprocess.run(
                ["file", str(png_file)],
                capture_output=True,
                text=True,
            )

            file_type = result.stdout.lower()
            # Valid PNG files should contain "png image data" in file output
            if "png image data" not in file_type:
                non_image_files.append((png_file, file_type))

        assert len(non_image_files) == 0, (
            f"Found {len(non_image_files)} files that are not PNG images: "
            f"{[(str(f), t.strip()) for f, t in non_image_files[:5]]}"
        )

    def test_step_4_verify_png_files_can_be_opened_by_image_viewers(
        self, demo_output_dir: Path
    ) -> None:
        """Step 4: Verify png files can be opened by image viewers.

        We test this by attempting to open with PIL/Pillow.
        """
        from PIL import Image

        # Find all PNG files
        png_files = list(demo_output_dir.rglob("*.png"))
        assert len(png_files) > 0, "No PNG files found in demo output"

        # Try to open each PNG file
        failed_files = []
        for png_file in png_files:
            try:
                with Image.open(png_file) as img:
                    # Verify it's actually a PNG
                    assert img.format == "PNG", f"{png_file}: format is {img.format}, not PNG"
                    # Verify it has reasonable dimensions
                    width, height = img.size
                    assert width > 0 and height > 0, f"{png_file}: invalid dimensions {width}x{height}"
            except Exception as e:
                failed_files.append((png_file, str(e)))

        assert len(failed_files) == 0, (
            f"Failed to open {len(failed_files)} PNG files: "
            f"{[(str(f), e) for f, e in failed_files[:5]]}"
        )

    def test_step_5_find_zero_byte_png_files(
        self, demo_output_dir: Path
    ) -> None:
        """Step 5: Run find demo_output -name *.png -size 0 and verify no results."""
        result = subprocess.run(
            ["find", str(demo_output_dir), "-name", "*.png", "-size", "0"],
            capture_output=True,
            text=True,
        )

        zero_byte_files = [line for line in result.stdout.strip().split("\n") if line]
        assert len(zero_byte_files) == 0, (
            f"Found {len(zero_byte_files)} zero-byte PNG files: {zero_byte_files}"
        )

    def test_all_demo_outputs_have_real_png_images(self) -> None:
        """Comprehensive test: verify all demo outputs have real PNG images."""
        demo_dirs = [
            Path("demo_output/nangate45_extreme_demo"),
            Path("demo_output/asap7_extreme_demo"),
            Path("demo_output/sky130_extreme_demo"),
        ]

        from PIL import Image

        total_pngs = 0
        for demo_dir in demo_dirs:
            if not demo_dir.exists():
                continue

            png_files = list(demo_dir.rglob("*.png"))
            if len(png_files) == 0:
                continue

            total_pngs += len(png_files)

            # Verify each PNG
            for png_file in png_files:
                # Check size
                size = png_file.stat().st_size
                assert size > 1000, f"{png_file}: size {size} <= 1000 bytes"

                # Check file type
                result = subprocess.run(
                    ["file", str(png_file)],
                    capture_output=True,
                    text=True,
                )
                assert "png image data" in result.stdout.lower(), (
                    f"{png_file}: not a PNG image"
                )

                # Try to open
                try:
                    with Image.open(png_file) as img:
                        assert img.format == "PNG"
                        width, height = img.size
                        assert width > 0 and height > 0
                except Exception as e:
                    pytest.fail(f"Failed to open {png_file}: {e}")

        assert total_pngs > 0, "No PNG files found in any demo output"

    def test_specific_heatmaps_are_real_images(
        self, demo_output_dir: Path
    ) -> None:
        """Verify specific expected heatmaps are real images."""
        from PIL import Image

        expected_heatmaps = [
            "before/heatmaps/placement_density.png",
            "before/heatmaps/routing_congestion.png",
            "before/heatmaps/rudy.png",
            "after/heatmaps/placement_density.png",
            "after/heatmaps/routing_congestion.png",
            "after/heatmaps/rudy.png",
            "comparison/placement_density_diff.png",
            "comparison/routing_congestion_diff.png",
            "comparison/rudy_diff.png",
        ]

        for heatmap_path in expected_heatmaps:
            png_file = demo_output_dir / heatmap_path
            assert png_file.exists(), f"Expected heatmap not found: {heatmap_path}"

            # Verify it's a real image
            size = png_file.stat().st_size
            assert size > 1000, f"{heatmap_path}: size {size} <= 1000 bytes"

            with Image.open(png_file) as img:
                assert img.format == "PNG", f"{heatmap_path}: not a PNG"
                width, height = img.size
                assert width >= 100 and height >= 100, (
                    f"{heatmap_path}: dimensions {width}x{height} too small"
                )
